name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        # Extra flags to ensure Flakes are enabled
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Build and Test
      run: nix develop .#ci -c cargo test --verbose

    - name: Lint with Clippy
      run: nix develop .#ci -c cargo clippy -p router -- -D warnings -W clippy::nursery -W clippy::pedantic
